[settings]
python.uv_venv_auto = true

[tools]
python = "latest"
uv = "latest"
"cargo:cargo-nextest" = "latest"
"go:github.com/go-delve/delve/cmd/dlv" = "latest"
pre-commit = "latest"
"pipx:maturin" = "latest"
"cargo:tokio-console" = "latest"
"npm:@fission-ai/openspec" = "latest"

[env]
_.python.venv = { path = ".venv", create = true }
RUST_LOG = "tui-poc=debug,gui=trace,end_to_end=debug,transport=debug,dap_gui_client=debug,debugger=debug,pythondap=debug,tui=debug,repl=debug"
