[tools]
python = "latest"
uv = "latest"
"cargo:cargo-nextest" = "latest"
"go:github.com/go-delve/delve/cmd/dlv" = "latest"
pre-commit = "latest"
"pipx:maturin" = "latest"

[env]
_.python.venv = { path = ".venv" }
RUST_LOG = "gui=trace,end_to_end=debug,transport=debug,dap_gui_client=debug,debugger=debug,pythondap=debug,tui=debug,repl=debug"
