[package]
name = "debugger"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eyre.workspace = true
crossbeam-channel.workspace = true
tracing.workspace = true
server = { path = "../server" }
serde.workspace = true
serde_json.workspace = true
transport = { path = "../transport" }
transport2 = { path = "../transport2" }
tokio = { version = "1.48", features = ["sync", "rt", "macros"] }
tokio-util.workspace = true
tokio-stream = "0.1.16"
futures = "0.3.31"
retry = "2.1.0"
dirs.workspace = true
launch_configuration = { path = "../launch_configuration" }
uuid = { version = "1.18.1", features = ["v4"] }
oneshot.workspace = true

[dev-dependencies]
color-eyre.workspace = true
ctor.workspace = true
tracing-subscriber.workspace = true
serde_json.workspace = true
tempfile = "3.23.0"
